### ISSUE TITLE
not working, please help

### ISSUE THREAD

**Issue by padmalakshmi143** [swappyison/zee5downloader#1]
It's a free movie:

https://www.zee5.com/movies/details/satyameva-jayate/0-0-74624

1) Downloaded JiocinemaDownloader where I can see the requirements.txt
2) Downloaded the Zee5 and copy those files in jiocinema
3) Moved all files to WKS-KEYS

python3 zee5urlscraper.py
entered the url: https://www.zee5.com/movies/details/satyameva-jayate/0-0-74624
access code: done

after that: (ERROR!!!)

Request for page 0 was successful.
Traceback (most recent call last):
  File "/var/www/WKS-KEYS/zee5urlscraper.py", line 43, in <module>
    data = response.json()  # Assuming the response is in JSON format
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by swappyison** [comment]
run zeeimprov.py with movie name is show_url.txt

**Comment by padmalakshmi143** [comment]
[show_urls.txt](https://github.com/swappyison/zee5downloader/files/12909904/show_urls.txt)

I have copied and placed the movie url in: show_urls.txt and then executed the command, here is the output.

-----
paddu@mac WKS-KEYS % python3 zeeimprov.py
  File "/Users/paddu/Desktop/WKS-KEYS/zeeimprov.py", line 12
    x-dd-token = config('X-DD-TOKEN')
    ^^^^^^^^^^
SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='?

**Comment by swappyison** [comment]
download the new script and place token values inside it

**Comment by padmalakshmi143** [comment]
I can able to see and grab these values, 
Authorization:
X-Access-Token:

but where can I find the x-dd-token: ? It's not showing anywhere in the developer tools, can u plz help.
